---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  - copy-files.yaml

patches:
  - target:
      name: copy-files
      kind: Task
    patch: |-
      - op: replace
        path: "/kind"
        value: "ClusterTask"
